from seleniumbase import BaseCase
import time
from page_objects.salesflow import SalesFlow
from functions.salesflow_functions import SalesFunctions
from utilities.customLogger import LogGen


class VerifyTest04(BaseCase):
    logger = LogGen.loggen()

    def Testcase04(self):
        self.logger.info("********** Verifying HarvestRight Website Opens *********")
        self.open(SalesFlow.puchaseorders_url)
        self.logger.info("********** HarvestRight Website Opens Successfully *********")
        self.logger.info("********** Verifying Login *********")
        time.sleep(1)
        SalesFunctions.login_page(self)
        self.logger.info("********** Login is Successful *********")
        self.logger.info("********** Verifying it opens the latest purchase order *********")
        time.sleep(2)
        self.click(SalesFlow.reference)
        time.sleep(1)
        self.click(SalesFlow.reference)
        time.sleep(2)
        self.click(SalesFlow.latest_po)
        self.logger.info("********** Latest purchase order opens successfully *********")
        time.sleep(2)
        self.logger.info("********** Verifying purchase order is downloaded *********")
        self.click(SalesFlow.download_btn)
        self.click(SalesFlow.download_po)
        self.logger.info("********** Successfully downloaded Purchase order *********")
        self.logger.info("********** Verifying RFQ is downloaded *********")
        self.click(SalesFlow.download_btn)
        self.click(SalesFlow.download_rfq)
        self.logger.info("********** Successfully downloaded RFQ *********")
        time.sleep(4)
        self.logger.info("********** Verifying receive products button working fine  *********")
        self.click(SalesFlow.receive_products)
        self.logger.info("********** It is working properly *********")
        self.logger.info("********** Verifying picking operations is downloaded*********")
        time.sleep(2)
        self.wait_for_element_clickable(SalesFlow.download_btn, timeout=21)
        self.click(SalesFlow.download_btn)
        time.sleep(2)
        self.click(SalesFlow.picking_operations)
        self.logger.info("********** Successfully downloaded picking operations *********")
        time.sleep(6)
        self.logger.info("********** Verifying delivery slip is downloaded *********")
        self.wait_for_element_clickable(SalesFlow.download_btn, timeout=21)
        self.click(SalesFlow.download_btn)
        time.sleep(2)
        self.click(SalesFlow.delivery_slip)
        self.logger.info("********** Successfully downloaded delivery slip *********")
        time.sleep(6)
        self.logger.info("********** Verifying Packages is downloaded *********")
        self.wait_for_element_clickable(SalesFlow.download_btn, timeout=21)
        self.click(SalesFlow.download_btn)
        time.sleep(2)
        self.wait_for_element_clickable(SalesFlow.packages, timeout=10)
        self.click(SalesFlow.packages)
        self.logger.info("********** Successfully downloaded Packages *********")
        time.sleep(2)
        self.logger.info("********** Verifying all print labels are downloaded *********")
        self.click(SalesFlow.print_labels)
        time.sleep(2)
        self.wait_for_element_clickable(SalesFlow.confirm_printlabels, timeout=27)
        self.click(SalesFlow.confirm_printlabels)
        time.sleep(7)
        self.wait_for_element_clickable(SalesFlow.print_labels, timeout=27)
        self.click(SalesFlow.print_labels)
        time.sleep(4)
        self.wait_for_element_clickable(SalesFlow.labels_2, timeout=41)
        self.click(SalesFlow.labels_2)
        time.sleep(2)
        self.wait_for_element_clickable(SalesFlow.confirm_printlabels, timeout=27)
        self.click(SalesFlow.confirm_printlabels)
        time.sleep(7)
        self.wait_for_element_clickable(SalesFlow.print_labels, timeout=27)
        self.click(SalesFlow.print_labels)
        time.sleep(4)
        self.wait_for_element_clickable(SalesFlow.labels_3, timeout=41)
        self.click(SalesFlow.labels_3)
        time.sleep(2)
        self.wait_for_element_clickable(SalesFlow.confirm_printlabels, timeout=27)
        self.click(SalesFlow.confirm_printlabels)
        time.sleep(7)
        self.wait_for_element_clickable(SalesFlow.print_labels, timeout=27)
        self.click(SalesFlow.print_labels)
        time.sleep(4)
        self.wait_for_element_clickable(SalesFlow.labels_4, timeout=41)
        self.click(SalesFlow.labels_4)
        time.sleep(2)
        self.wait_for_element_clickable(SalesFlow.confirm_printlabels, timeout=27)
        self.click(SalesFlow.confirm_printlabels)
        time.sleep(7)
        self.wait_for_element_clickable(SalesFlow.print_labels, timeout=27)
        self.click(SalesFlow.print_labels)
        time.sleep(4)
        self.wait_for_element_clickable(SalesFlow.labels_5, timeout=41)
        self.click(SalesFlow.labels_5)
        time.sleep(2)
        self.wait_for_element_clickable(SalesFlow.confirm_printlabels, timeout=27)
        self.click(SalesFlow.confirm_printlabels)
        time.sleep(7)
        self.wait_for_element_clickable(SalesFlow.print_labels, timeout=27)
        self.click(SalesFlow.print_labels)
        time.sleep(4)
        self.wait_for_element_clickable(SalesFlow.labels_6, timeout=41)
        self.click(SalesFlow.labels_6)
        time.sleep(2)
        self.wait_for_element_clickable(SalesFlow.confirm_printlabels, timeout=21)
        self.click(SalesFlow.confirm_printlabels)
        self.logger.info("********** Successfully downloaded all print labels *********")







