from seleniumbase import BaseCase
from utilities.customLogger import LogGen


class SalesFlow(BaseCase):
    logger = LogGen.loggen()

    harvestright_url = "https://silverdaletech-harvest-right-do-not-delete-automatio-9873451.dev.odoo.com/web#cids=1&action=menu"
    quotation_url = "https://silverdaletech-harvest-right-do-not-delete-automatio-9873451.dev.odoo.com/web#action=315&model=sale.order&view_type=list&menu_id=183&cids=1"
    email = "//input[@id='login']"
    pswrd = "//input[@id='password']"
    login = "//button[contains(text(),'Log in')]"
    sales_module = "//body/div[2]/div[1]/div[1]/div[1]/a[39]/img[1]"
    new_quote = "//button[contains(text(),'New')]"
    customer = "//input[@id='partner_id']"
    exp_date = "//input[@id='validity_date']"
    pay_terms = "//input[@id='payment_term_id']"
    add_product = "//a[contains(text(),'Add a product')]"
    test_product1 = "//tbody/tr[1]/td[2]/div[1]/div[1]/div[1]/div[1]/input[1]"
    tp1_quantity = "//tbody/tr[1]/td[4]/div[1]/input[1]"
    tp1_taxes = "//tbody/tr[1]/td[10]/div[1]/div[1]/div[1]/div[1]/div[1]/input[1]"
    test_product2 = "//tbody/tr[2]/td[2]/div[1]/div[1]/div[1]/div[1]/input[1]"
    tp2_quantity = "//tbody/tr[2]/td[4]/div[1]/input[1]"
    test_product3 = "//tbody/tr[3]/td[2]/div[1]/div[1]/div[1]/div[1]/input[1]"
    tp3_quantity = "//tbody/tr[3]/td[4]/div[1]/input[1]"
    first_quot_rcord = "//tbody/tr[1]/td[4]"
    send_by_email = "//span[contains(text(),'Send by Email')]"
    input_email = "//input[@id='email']"
    input_phone = "//input[@id='phone']"
    input_mobile = "//input[@id='mobile']"
    save_close_btn = "//button[contains(text(),'Save & Close')]"
    send_btn = "//body/div[3]/div[6]/div[1]/div[1]/div[1]/div[1]/div[1]/footer[1]/footer[1]/button[1]"
    customer_preview = "//body/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/button[1]"
    sign_n_pay_iframe = "//body/div[2]/div[1]/div[1]/iframe[2]"
    sign_n_pay = "//a[contains(text(),'Sign & Pay')]"
    accept_n_sign = "//button[normalize-space()='Accept & Sign']"
    creditcard = "//b[contains(text(),'Credit Card (powered by Authorize)')]"
    pay = "//button[normalize-space()='Pay']"
    payment_verify = "//p[contains(text(),'Your payment has been successfully processed. Than')]"
    download = "//a[normalize-space()='Download']"
    edit_mode = "//a[normalize-space()='Back to edit mode']"
    verify_quotation_send = "//button[contains(text(),'Quotation Sent')]"
    verify_sales_order = "//button[contains(text(),'Sales Order')]"
    verify_po = "//span[contains(text(),'Purchase')]"
    verify_tasks = "//span[contains(text(),'Tasks')]"
    verify_projects = "//span[contains(text(),'Projects')]"
    verify_mo = "//span[contains(text(),'Manufacturing')]"
    download_btn = "//span[contains(text(),'Download')]"
    download_QO = "//span[contains(text(),'Quotation / Order')]"
    timesheets = "//span[contains(text(),'Timesheets')]"
    purchase = "//button[@name='action_view_purchase_orders']"
    cardnmbr = "#o_authorize_card_4"
    expiration_month = "#o_authorize_month_4"
    expiration_year = "#o_authorize_year_4"
    card_code = "#o_authorize_code_4"
    rfq_send = "//button[contains(text(),'RFQ Sent')]"
    print_rfq = "//span[contains(text(),'Print RFQ')]"
    confirm_order = "//span[contains(text(),'Confirm Order')]"
    purchase_order = "//button[normalize-space()='Purchase Order']"
    send_po_email = "//span[contains(text(),'Send PO by Email')]"
    receipt = "//span[normalize-space()='Receipt']"
    send_po = "//span[normalize-space()='Send']"
    download_po = "//span[@role='menuitem'][normalize-space()='Purchase Order']"
    download_rfq = "//span[contains(text(),'Request for Quotation')]"
    receive_products = "//span[contains(text(),'Receive Products')]"
    print_labels = "//span[contains(text(),'Print Labels')]"
    confirm_printlabels = "//span[contains(text(),'Confirm')]"
    labels_2 = "//label[contains(text(),'4 x 7 with price')]"
    labels_3 = "//label[normalize-space()='4 x 12']"
    labels_4 = "//label[contains(text(),'4 x 12 with price')]"
    labels_5 = "//label[normalize-space()='ZPL Labels']"
    labels_6 = "//label[contains(text(),'ZPL Labels with price')]"
    picking_operations = "//span[contains(text(),'Picking Operations')]"
    delivery_slip = "//span[contains(text(),'Delivery Slip')]"
    packages = "//span[contains(text(),'Packages')]"
    pic_pdf = "//body/div[2]/div[1]/div[2]/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[3]/div[2]/div[2]/div[3]/div[1]/div[1]/div[1]/div[1]"
    quality_checks = "//button[@name='check_quality']//span[contains(text(),'Quality Checks')]"
    save_manually = "//i[@class='fa fa-cloud-upload fa-fw']"
    puchaseorders_url = "https://silverdaletech-harvest-right-do-not-delete-automatio-9873451.dev.odoo.com/web#action=418&model=purchase.order&view_type=list&menu_id=249&cids=1"
    fav = "//span[contains(text(),'Favorites')]"
    nothing_to_bill = "//body/div[2]/div[1]/div[1]/div[2]/div[2]/div[1]/div[3]/div[1]/span[1]/span[1]"
    latest_po = "//tbody/tr[1]/td[6]"
    reference = "//span[contains(text(),'Reference')]"
    take_a_pic = "//button[contains(text(),'Take a Picture')]"
    input_type = "//body/div[3]/div[6]/div[1]/div[1]/div[1]/div[1]/div[1]/main[1]/div[1]/div[1]/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/input[1]"
    validate_btn = "//span[contains(text(),'Validate')]"
    set_quantities = "//span[contains(text(),'Set quantities')]"
    put_in_pack = "//span[contains(text(),'Put in Pack')]"
    val_btn = "//body/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/button[1]"
    click_done = "//tbody/tr[1]/td[2]"
    done = "//input[@inputmode='decimal']"
    menu_lot_serial = "//i[@class='o_optional_columns_dropdown_toggle oi oi-fw oi-settings-adjust']"
    serial_numbers = "//label[contains(text(),'Serial Numbers')]"
    serial_click = "//td[@name='product_uom_qty']"
    serial_1 = "//tbody/tr[1]/td[3]/div[1]/div[1]/textarea[1]"
    serial_2 = "//tbody/tr[2]/td[3]/div[1]/div[1]/textarea[1]"
    serial_3 = "//tbody/tr[3]/td[3]/div[1]/div[1]/textarea[1]"
    serial_4 = "//tbody/tr[4]/td[3]/div[1]/div[1]/textarea[1]"
    confirm_serial = "//span[contains(text(),'Confirm')]"
    operations_text = "//a[contains(text(),'Operations')]"
    input_serial = "div[class='o_field_many2many_selection d-inline-flex w-100'] input[type='text']"
    verify_done_state = "//button[contains(text(),'Done')]"
    ok_btn = "//button[contains(text(),'Ok')]"
    create_backorder = "//span[contains(text(),'Create Backorder')]"
    backorder_ok_btn = "//button[@class='btn btn-primary o-default-button']"
    inside_menu_serial = "//i[@class='fa fa-fw o_button_icon fa-list']"
    assign_serial_no = "//div[@class='modal d-block o_technical_modal']//span[contains(text(),'Assign Serial Numbers')]"
    confirm_serial_no = "//div[@class='modal d-block o_technical_modal']//span[contains(text(),'Confirm')]"
    blank_space = "//td[contains(text(),'​')]"
    add_a_line = "//tbody/tr[1]/td[1]/a[1]"
    input_lotserial = "//td[@name='lot_name']"
    type_lotserial = "//tbody/tr[1]/td[3]/div[1]/div[1]/textarea[1]"
    done_lot = "//tbody/tr[1]/td[5]/div[1]/input[1]"
    confirm_lot = "//span[contains(text(),'Confirm')]"
    blank_spaces = "//tbody/tr[4]/td[1]"
    orders = "//span[contains(text(),'Orders')]"
    purchasee_orders = "//a[contains(text(),'Purchase Orders')]"
    create_bill = "//span[contains(text(),'Create Bill')]"
    confirm_bill = "//span[contains(text(),'Confirm')]"
    bill_date = "//input[@id='invoice_date']"
    register_payment = "//span[contains(text(),'Register Payment')]"
    create_payment = "//span[contains(text(),'Create Payment')]"
    sale_order_status = "//span[contains(text(),'Sales Order')]"

